### ISSUE TITLE
Testing, Testing, Testing!

### ISSUE THREAD

**Issue by justinmuskopf** [justinmuskopf/taco_tuesday_backend#32]
We need a unit test class for every REST controller (and each of  their endpoints) and several ITs covering both happy/sad paths.

**Comment by svetlana739** [comment]
Hello. Could you give me more details about it.

**Comment by justinmuskopf** [comment]
@svetlana739 I would like to have a test written for every API controller endpoint (e.g. `GET /employees`).

Here is some good documentation on getting started with Spring Boot REST controller tests: https://www.baeldung.com/spring-boot-testing#unit-testing-with-webmvctest

Are you interested in working this task?

**Comment by svetlana739** [comment]
Hello, thank you for the answer. I need to sorry. I didn't pay attention before I wrote you. I think you need JUnit because your program on Java programming language . I know Python programming language. Sorry.

**Comment by justinmuskopf** [comment]
### /employees
* `GET`
  - [x] happy path
  - [x] sad path, no `apiKey`
  - [x] sad path, invalid `apiKey`

* `GET /{slackId}`
  - [x] happy path
  - [x] sad path, invalid `slackId`
  - [x] sad path, no `apiKey`
  - [x] sad path, invalid `apiKey`

* `POST`
  - [x] happy path
  - [x] sad path, no `apiKey`
  - [x] sad path, invalid `apiKey`
  - [x] sad path, invalid `slackId` in body
  - [x] sad path, no `slackId` in body
  - [x] sad path, invalid `fullName` in body
  - [x] sad path, no `fullName` in body

* `PATCH`
  - [x] happy path
  - [x] sad path, no `apiKey`
  - [x] sad path, invalid `apiKey`
  - [x] sad path, invalid `slackId` in one of list of employees
  - [x] sad path, no `slackId` in one of list of employees
  - [x] sad path, invalid `fullName` one of list of employees (empty string)

* `PATCH /{slackId}`
  - [x] happy path
  - [x] sad path, no `apiKey`
  - [x] sad path, invalid `apiKey`
  - [x] sad path, invalid `slackId` path variable
  - [x] sad path, invalid full name (empty string)

### /orders
#### /orders/full
* `GET`
  - [x] happy path
  - [x] happy path (filtered by `slackId` header)

* `GET /{orderId}`
  - [x] happy path
  - [x] sad path, invalid `orderId`

* `POST`
  - [x] happy path
  - [x] sad path, `individualOrders` is empty
  - [x] sad path, negative count for a taco field
  - [x] sad path, negative price for order
#### /orders/individual
* `GET`
  - [x] happy path
  - [x] happy path, filtered by slack id

* `GET /{orderId}`
  - [x] happy path
  - [x] sad path, invalid `orderId`

### /tacos
* `GET`
  - [x] happy path

**Comment by justinmuskopf** [comment]
Finished by PR #48
