### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by justinmuskopf** [justinmuskopf/taco_tuesday_backend#8]
This is an investigative task.

As I'm implementing things I realize how many times we might just accept a malformed string (e.g. in names) or invalid numerical value.

We need to find everywhere that we're doing this and make tasks that detail the changes.

**Comment by AJD-** [comment]
Probably should add a maximum amount of ~20 for each taco per user

**Comment by justinmuskopf** [comment]
> Probably should add a maximum amount of ~20 for each taco per user

Noted! Decided to handle this on the front end.
I snuck it into [this commit](https://github.com/justinmuskopf/taco_tuesday_slack_app/pull/13/commits/9a37773b7152d7dbe02047902bf03305e42240d4).

**Comment by justinmuskopf** [comment]
Look into and create some `Validators` for every domain object.
https://stackoverflow.com/questions/12146298/spring-mvc-how-to-perform-validation

**Comment by justinmuskopf** [comment]
Finished by PR #48
